language: python

python:
  - "2.7"
  - "3.4"

before_install:
  - echo $TRAVIS_BUILD_DIR
  - sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran

install: 
  - python setup.py install

script: py.test