language: python

python:
  - "2.7"
  - "3.6"

addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - libatlas-base-dev
    - gfortran

before_install:
  - wget http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz
  - tar -xvf nlopt-2.4.2.tar.gz

install:
  - cd nlopt-2.4.2
  - PYTHON=$(which python) ./configure --prefix=$(dirname $(dirname $(which python))) --enable-shared
  - make
  - make install
  - cd $TRAVIS_BUILD_DIR
  - pip install --upgrade pip
  - pip install --upgrade pytest pytest-cov
  - pip install codecov unipath requests
  - pip install git+https://github.com/nicta/revrand.git@v0.6.5#egg=revrand-0.6.5
  - pip install matplotlib
  - pip install -e .

script:
  - py.test --cov=./

cache:
  - apt
  - pip
  - directories:
    - $HOME/.cache/pip

after_success:
  - codecov
